<?php
/*
 * Copyright (c) 2026 Yellow Teak
 * SPDX-License-Identifier: MIT
 */

/** @var ChangePassword $block */

use YellowTeak\ChangeCustomerPassword\Block\Adminhtml\Tab\ChangePassword;
?>
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= $block->escapeHtml(__('Change Password')) ?></span>
    </div>
    <div class="admin__fieldset">
        <div class="admin__field">
            <label class="admin__field-label" for="new_password"><?= $block->escapeHtml(__('New Password')) ?></label>
            <div class="admin__field-control">
                <input type="password" id="new_password" name="change_password[new_password]"
                       class="admin__control-text" data-form-part="customer_form"
                       autocomplete="new-password" required minlength="8"/>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="password_confirmation"><?= $block->escapeHtml(__('Password Confirmation')) ?></label>
            <div class="admin__field-control">
                <input type="password" id="password_confirmation" name="change_password[password_confirmation]"
                       class="admin__control-text" data-form-part="customer_form"
                       autocomplete="new-password" required minlength="8"/>
            </div>
        </div>
    </div>
    <div class="fieldset-wrapper-title">
        <span class="title"><?= $block->escapeHtml(__('Current User Identity Verification')) ?></span>
    </div>
    <div class="admin__fieldset">
        <div class="admin__field">
            <label class="admin__field-label" for="admin_password"><?= $block->escapeHtml(__('Your Password')) ?></label>
            <div class="admin__field-control">
                <input type="password" id="admin_password" name="change_password[admin_password]"
                       class="admin__control-text" data-form-part="customer_form"
                       autocomplete="current-password" required/>
            </div>
        </div>
    </div>
</div>
